# Generated by Django 2.0.2 on 2018-04-19 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=40)),
                ('press', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('author', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('total', models.IntegerField()),
                ('stock', models.IntegerField()),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField()),
                ('return_date', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmanage.Book')),
            ],
            options={
                'db_table': 'borrowrecord',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=40)),
                ('type', models.BooleanField()),
            ],
            options={
                'db_table': 'card',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'manager',
            },
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmanage.Card'),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='return_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmanage.Manager'),
        ),
    ]
